### ISSUE TITLE
Upgrade bwa to latest to support linux arm64/aarch64

### ISSUE THREAD

**Issue by Yikun** [crisprVerse/Rbwa#1]
We are supporting the BioConductor on Linux aarch64:

- [Bioc-devel] Support for Linux ARM64: https://stat.ethz.ch/pipermail/bioc-devel/2023-January/019398.html

But hit the issue on RBWA: https://github.com/Yikun/BBS/issues/20 .

Actually, the upstream bwa already support the linux aarch64 [1] since 2022 and also enable the linux arm CI [2].

Could you upgrade bwa to latest to include [1][2]? @Jfortin1

Please let us know if you need any help! Thanks

[1] https://github.com/lh3/bwa/pull/359
[2] https://github.com/lh3/bwa/pull/367

**Comment by Yikun** [comment]
also cc @martin-g (who involved the bwa linux aarch64 support)

**Comment by Jfortin1** [comment]
@Yikun On it

**Comment by Yikun** [comment]
@Jfortin1 Awesome! Thanks for your help!
